services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.ssh/authorized_keys:/home/vscode/.ssh/authorized_keys:cached
      - ~/.config/gh:/home/vscode/.config/gh:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:cached
    command: sleep infinity
    working_dir: /workspace
    init: true
